export { default as Employees } from "./Employees";
export { default as Calendar } from "./Calendar";
export { default as Notes } from "./Notes";
export { default as Urgent } from "./Urgent";
export { default as Profile } from "./Profile";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Dashboard } from "./Dashboard";
export { default as LineChart } from "./Charts/LineChart";
